export const colors = {
  indigo: '#818cf8',
  emerald: '#34d399',
  red: '#f87171',
  amber: '#f59e0b',
  slate300: '#cbd5e1',
  slate400: '#94a3b8',
  slate500: '#64748b',
  slate700: '#334155',
  slate800: '#1e293b',
  slate900: '#0f172a',
  appBg: '#0b1120',
  appSurface: '#111827',
  appCard: '#1e293b',
} as const;

export const sv = {
  text: 'var(--svg-text)',
  textFaint: 'var(--svg-text-faint)',
  axis: 'var(--svg-axis)',
  grid: 'var(--svg-grid)',
  gridSubtle: 'var(--svg-grid-subtle)',
  fillRed: 'var(--fill-red)',
  fillAmber: 'var(--fill-amber)',
  fillEmerald: 'var(--fill-emerald)',
  fillIndigo: 'var(--fill-indigo)',
  fillOverlap: 'var(--fill-overlap)',
  fillRedSubtle: 'var(--fill-red-subtle)',
  fillEmeraldSubtle: 'var(--fill-emerald-subtle)',
  fillIndigoSubtle: 'var(--fill-indigo-subtle)',
  fillAmberSubtle: 'var(--fill-amber-subtle)',
  borderRed: 'var(--border-red)',
  borderEmerald: 'var(--border-emerald)',
  borderIndigo: 'var(--border-indigo)',
  borderAmber: 'var(--border-amber)',
  appBg: 'var(--color-app-bg)',
} as const;
